eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.142.198:8761/eureka/
server:
  port: 8763
  tomcat:
    max-threads: 50000
spring:
  application:
    name: service-fg

#####################################################################################################
# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.142.198:3306/dengke?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    ##?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: duoduo
    password: OJNIS*MO73C0ZDrT
    jpa:
#    hibernate:
#      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
#      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      show-sql: true
#####################################################################################################

  redis:
    #数据库索引
    database: 0
    host: 172.18.142.198
    port: 6379
    password: OJNIS*MO73C0ZDrT
    jedis:
      pool:
        #最大连接数
        max-active: 500
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
    #cluster:
      #nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

#####################################################################################################
# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  type-aliases-package: com.dz.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
#####################################################################################################


#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
  path: C:\\logs\\info.log
#####################################################################################################


